[alembic]
script_location = alembic
prepend_sys_path = .
sqlalchemy.url = %(DB_URL)s

[post_write_hooks]
hooks =
hook_type = console_scripts

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = logging.StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
